#build-job:
#  stage: build
#  script:
#    - echo "Hello, $GITLAB_USER_LOGIN!"

#test-job1:
#  stage: test
#  script:
#    - echo "This job tests something"

#test-job2:
#  stage: test
#  script:
#    - echo "This job tests something, but takes more time than test-job1."
#    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
#    - echo "which simulates a test that runs 20 seconds longer than test-job1"
#    - sleep 20

#deploy-prod:
#  image: node:latest
#  stage: deploy
#  script:
#      - apt-get update -qy
#      - apt-get install -y ruby-dev
#      - gem install dpl
#      - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
      #- git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/quiz-champ-projet-integrateur.git
      #- git push -f -q heroku HEAD:master
#  environment: production
